# server-lib-log
logs:
  run:
    output: logs/run.log-*-*-*
    level: ALL
  slowsql:
    output: logs/slow-sql.log-*-*-*
    level: ALL
  access:
    output: logs/access.log-*-*-*
    level: ALL
  error:
    output: logs/error.log-*-*-*
    level: ALL
    traceoffset: 1
  user:
    output: logs/user.log-*-*-*
    level: ALL
  friend:
    output: logs/friend.log-*-*-*
    level: ALL

# server-lib-mysql
s-mysql:
  default-master:
    addr: 127.0.0.1
    username: root
    password: '123456'
    database: db_game
    options: charset=utf8mb4&parseTime=True
    maxidle: 16
    maxopen: 128
    maxlifetime: 300s
    slowsqltime: 2s
    slowlog: slowsql
    errorlog: error
    statlog: run
  default-slave:
    addr: 127.0.0.1
    username: root
    password: '123456'
    database: db_game
    options: charset=utf8mb4&parseTime=True
    maxidle: 16
    maxopen: 128
    maxlifetime: 300s
    slowsqltime: 2s
    slowlog: slowsql
    errorlog: error
    statlog: run

# server-lib-redis
s-redis:
  default:
    Addr: 127.0.0.1:6379,127.0.0.1:6379,127.0.0.1:6379
    Password: '123456'
    MaxActive: 128
    MaxIdle: 16
    IdleTimeout: 240s
    ConnectTimeout: 500ms
    ReadTimeout: 500ms
    WriteTimeout: 1000ms
    TestInterval: 60s
