//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//LevelRaceUsergroupConfig auto
type LevelRaceUsergroupConfig struct {
	ID          int   //#
	LEVELRANGE  []int //关卡区间 前闭后开 -1表示满级玩家/精英赛玩家；0表示主线最大关卡
	RATINGRANGE []int //玩家积分范围，左闭右开
	GROUPTYPE   []int //玩家积分对应分组
}

//ILevelRaceUsergroupConfig auto
type ILevelRaceUsergroupConfig interface {
	GetID() int
	GetLEVELRANGELen() int
	GetLEVELRANGEByIndex(index int) int
	GetRATINGRANGELen() int
	GetRATINGRANGEByIndex(index int) int
	GetGROUPTYPELen() int
	GetGROUPTYPEByIndex(index int) int
}

//GetID auto
func (l *LevelRaceUsergroupConfig) GetID() int {
	return l.ID
}

//GetLEVELRANGELen auto
func (l *LevelRaceUsergroupConfig) GetLEVELRANGELen() int {
	return len(l.LEVELRANGE)
}

//GetLEVELRANGEByIndex auto
func (l *LevelRaceUsergroupConfig) GetLEVELRANGEByIndex(index int) int {
	return l.LEVELRANGE[index]
}

//GetRATINGRANGELen auto
func (l *LevelRaceUsergroupConfig) GetRATINGRANGELen() int {
	return len(l.RATINGRANGE)
}

//GetRATINGRANGEByIndex auto
func (l *LevelRaceUsergroupConfig) GetRATINGRANGEByIndex(index int) int {
	return l.RATINGRANGE[index]
}

//GetGROUPTYPELen auto
func (l *LevelRaceUsergroupConfig) GetGROUPTYPELen() int {
	return len(l.GROUPTYPE)
}

//GetGROUPTYPEByIndex auto
func (l *LevelRaceUsergroupConfig) GetGROUPTYPEByIndex(index int) int {
	return l.GROUPTYPE[index]
}
