//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//LevelRaceConfig auto
type LevelRaceConfig struct {
	ID           int   //#
	STARTDAY     int   //活动开启时间，每周的星期几；1代表星期1，以此类推
	STARTTIME    []int //24小时制，小时|分钟|秒
	DURATION     int   //活动持续时间，单位为分钟；活动开启时间+活动持续时间即为活动运行结束时间
	TARGET       int   //活动目标关卡数
	RESULTRATING []int //玩家在每轮结束时可获得的评价分数，配置项分别对应第一名到第三名且达成了活动目标可得到的评价分数，第四到第五名可获得的评价分数
	RESETFACTOR  int   //软重置系数
}

//ILevelRaceConfig auto
type ILevelRaceConfig interface {
	GetID() int
	GetSTARTDAY() int
	GetSTARTTIMELen() int
	GetSTARTTIMEByIndex(index int) int
	GetDURATION() int
	GetTARGET() int
	GetRESULTRATINGLen() int
	GetRESULTRATINGByIndex(index int) int
	GetRESETFACTOR() int
}

//GetID auto
func (l *LevelRaceConfig) GetID() int {
	return l.ID
}

//GetSTARTDAY auto
func (l *LevelRaceConfig) GetSTARTDAY() int {
	return l.STARTDAY
}

//GetSTARTTIMELen auto
func (l *LevelRaceConfig) GetSTARTTIMELen() int {
	return len(l.STARTTIME)
}

//GetSTARTTIMEByIndex auto
func (l *LevelRaceConfig) GetSTARTTIMEByIndex(index int) int {
	return l.STARTTIME[index]
}

//GetDURATION auto
func (l *LevelRaceConfig) GetDURATION() int {
	return l.DURATION
}

//GetTARGET auto
func (l *LevelRaceConfig) GetTARGET() int {
	return l.TARGET
}

//GetRESULTRATINGLen auto
func (l *LevelRaceConfig) GetRESULTRATINGLen() int {
	return len(l.RESULTRATING)
}

//GetRESULTRATINGByIndex auto
func (l *LevelRaceConfig) GetRESULTRATINGByIndex(index int) int {
	return l.RESULTRATING[index]
}

//GetRESETFACTOR auto
func (l *LevelRaceConfig) GetRESETFACTOR() int {
	return l.RESETFACTOR
}
