//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//RobotTeamChat auto
type RobotTeamChat struct {
	ID      int    //#
	Type    int    //聊天信息类型（1：初次入会2：请求体力）
	TextNum string //多语言编号
}

//IRobotTeamChat auto
type IRobotTeamChat interface {
	GetID() int
	GetType() int
	GetTextNum() string
}

//GetID auto
func (r *RobotTeamChat) GetID() int {
	return r.ID
}

//GetType auto
func (r *RobotTeamChat) GetType() int {
	return r.Type
}

//GetTextNum auto
func (r *RobotTeamChat) GetTextNum() string {
	return r.TextNum
}
