//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//RobotTeamInitial auto
type RobotTeamInitial struct {
	ID          int     //#
	LevelRange  []int   //关卡分段（左开右闭，-1为满级|精英赛）
	RobotType   []int   //行为类型：1:积极型；2：平衡型；3：懒惰型
	RobotWeight []int   //单个机器人随机出时的类型权重
	RobotAiID   [][]int //对应类型对应的行为id(robot_team表ID)
}

//IRobotTeamInitial auto
type IRobotTeamInitial interface {
	GetID() int
	GetLevelRangeLen() int
	GetLevelRangeByIndex(index int) int
	GetRobotTypeLen() int
	GetRobotTypeByIndex(index int) int
	GetRobotWeightLen() int
	GetRobotWeightByIndex(index int) int
	GetRobotAiIDLen() int
	GetRobotAiIDByIndex(index int) []int
}

//GetID auto
func (r *RobotTeamInitial) GetID() int {
	return r.ID
}

//GetLevelRangeLen auto
func (r *RobotTeamInitial) GetLevelRangeLen() int {
	return len(r.LevelRange)
}

//GetLevelRangeByIndex auto
func (r *RobotTeamInitial) GetLevelRangeByIndex(index int) int {
	return r.LevelRange[index]
}

//GetRobotTypeLen auto
func (r *RobotTeamInitial) GetRobotTypeLen() int {
	return len(r.RobotType)
}

//GetRobotTypeByIndex auto
func (r *RobotTeamInitial) GetRobotTypeByIndex(index int) int {
	return r.RobotType[index]
}

//GetRobotWeightLen auto
func (r *RobotTeamInitial) GetRobotWeightLen() int {
	return len(r.RobotWeight)
}

//GetRobotWeightByIndex auto
func (r *RobotTeamInitial) GetRobotWeightByIndex(index int) int {
	return r.RobotWeight[index]
}

//GetRobotAiIDLen auto
func (r *RobotTeamInitial) GetRobotAiIDLen() int {
	return len(r.RobotAiID)
}

//GetRobotAiIDByIndex auto
func (r *RobotTeamInitial) GetRobotAiIDByIndex(index int) []int {
	return r.RobotAiID[index]
}
