// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: guild.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//公会开放类型
type GuildOpenType int32

const (
	GuildOpenType_NONE1 GuildOpenType = 0
	GuildOpenType_CLOSE GuildOpenType = 1
	GuildOpenType_OPEN  GuildOpenType = 2
)

// Enum value maps for GuildOpenType.
var (
	GuildOpenType_name = map[int32]string{
		0: "NONE1",
		1: "CLOSE",
		2: "OPEN",
	}
	GuildOpenType_value = map[string]int32{
		"NONE1": 0,
		"CLOSE": 1,
		"OPEN":  2,
	}
)

func (x GuildOpenType) Enum() *GuildOpenType {
	p := new(GuildOpenType)
	*p = x
	return p
}

func (x GuildOpenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildOpenType) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_proto_enumTypes[0].Descriptor()
}

func (GuildOpenType) Type() protoreflect.EnumType {
	return &file_guild_proto_enumTypes[0]
}

func (x GuildOpenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildOpenType.Descriptor instead.
func (GuildOpenType) EnumDescriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{0}
}

type RankType int32

const (
	RankType_GLOBAL  RankType = 0 //全局
	RankType_COUNTRY RankType = 1 //国家
)

// Enum value maps for RankType.
var (
	RankType_name = map[int32]string{
		0: "GLOBAL",
		1: "COUNTRY",
	}
	RankType_value = map[string]int32{
		"GLOBAL":  0,
		"COUNTRY": 1,
	}
)

func (x RankType) Enum() *RankType {
	p := new(RankType)
	*p = x
	return p
}

func (x RankType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankType) Descriptor() protoreflect.EnumDescriptor {
	return file_guild_proto_enumTypes[1].Descriptor()
}

func (RankType) Type() protoreflect.EnumType {
	return &file_guild_proto_enumTypes[1]
}

func (x RankType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankType.Descriptor instead.
func (RankType) EnumDescriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{1}
}

// 返回公会状态
type GetGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode uint32 `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` //  ...
}

func (x *GetGuild) Reset() {
	*x = GetGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuild) ProtoMessage() {}

func (x *GetGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuild.ProtoReflect.Descriptor instead.
func (*GetGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{0}
}

func (x *GetGuild) GetRetCode() uint32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *GetGuild) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGuild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//公会基本信息
type GuildBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                //公会ID
	Badge      string        `protobuf:"bytes,2,opt,name=Badge,proto3" json:"Badge,omitempty"`                           //　公会徽章
	OpenType   GuildOpenType `protobuf:"varint,3,opt,name=openType,proto3,enum=GuildOpenType" json:"openType,omitempty"` //  公会类型（0-不可加入，1-可加入，其它后面再扩展）
	LimitLevel int32         `protobuf:"varint,4,opt,name=limitLevel,proto3" json:"limitLevel,omitempty"`                //限制等级
	Score      int64         `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`                          //公会积分
	Leader     int64         `protobuf:"varint,6,opt,name=leader,proto3" json:"leader,omitempty"`                        // 会长
	Name       string        `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`                             // 公会名称
	Desc       string        `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`                             // 公会简介
	Country    string        `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`                       // 国家
	MemberNum  int32         `protobuf:"varint,10,opt,name=memberNum,proto3" json:"memberNum,omitempty"`                 // 成员数量
	HelpCount  int32         `protobuf:"varint,11,opt,name=helpCount,proto3" json:"helpCount,omitempty"`                 // 公会帮助次数
	Robot      bool          `protobuf:"varint,12,opt,name=robot,proto3" json:"robot,omitempty"`                         // 机器人
	FrameIcon  string        `protobuf:"bytes,13,opt,name=frameIcon,proto3" json:"frameIcon,omitempty"`                  //边框
	Star       int32         `protobuf:"varint,14,opt,name=star,proto3" json:"star,omitempty"`                           // 星星 满级玩法，星星个数，可以理解为level2
}

func (x *GuildBaseInfo) Reset() {
	*x = GuildBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildBaseInfo) ProtoMessage() {}

func (x *GuildBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildBaseInfo.ProtoReflect.Descriptor instead.
func (*GuildBaseInfo) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{1}
}

func (x *GuildBaseInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildBaseInfo) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *GuildBaseInfo) GetOpenType() GuildOpenType {
	if x != nil {
		return x.OpenType
	}
	return GuildOpenType_NONE1
}

func (x *GuildBaseInfo) GetLimitLevel() int32 {
	if x != nil {
		return x.LimitLevel
	}
	return 0
}

func (x *GuildBaseInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GuildBaseInfo) GetLeader() int64 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *GuildBaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildBaseInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GuildBaseInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GuildBaseInfo) GetMemberNum() int32 {
	if x != nil {
		return x.MemberNum
	}
	return 0
}

func (x *GuildBaseInfo) GetHelpCount() int32 {
	if x != nil {
		return x.HelpCount
	}
	return 0
}

func (x *GuildBaseInfo) GetRobot() bool {
	if x != nil {
		return x.Robot
	}
	return false
}

func (x *GuildBaseInfo) GetFrameIcon() string {
	if x != nil {
		return x.FrameIcon
	}
	return ""
}

func (x *GuildBaseInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

//公会成员信息
type GuildMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            //成员ID
	Score          int32  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`      //成员积分
	Level          int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`      //成员等级
	Name           string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`         //成员名
	HeadIcon       string `protobuf:"bytes,5,opt,name=headIcon,proto3" json:"headIcon,omitempty"` //头像
	Help           int32  `protobuf:"varint,6,opt,name=help,proto3" json:"help,omitempty"`        //
	Like           int32  `protobuf:"varint,7,opt,name=like,proto3" json:"like,omitempty"`
	Country        string `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`                 //国家
	Channel        int32  `protobuf:"varint,9,opt,name=channel,proto3" json:"channel,omitempty"`                //
	Star           int32  `protobuf:"varint,10,opt,name=star,proto3" json:"star,omitempty"`                     // 累计积分 (星星)
	Trophy         int32  `protobuf:"varint,11,opt,name=trophy,proto3" json:"trophy,omitempty"`                 // 成就奖杯
	StarActivityId int64  `protobuf:"varint,12,opt,name=starActivityId,proto3" json:"starActivityId,omitempty"` // star字段所属的活动ID，若该ID与当前正在开启的活动ID不一致，则返回0
}

func (x *GuildMember) Reset() {
	*x = GuildMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMember) ProtoMessage() {}

func (x *GuildMember) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMember.ProtoReflect.Descriptor instead.
func (*GuildMember) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{2}
}

func (x *GuildMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildMember) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GuildMember) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GuildMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildMember) GetHeadIcon() string {
	if x != nil {
		return x.HeadIcon
	}
	return ""
}

func (x *GuildMember) GetHelp() int32 {
	if x != nil {
		return x.Help
	}
	return 0
}

func (x *GuildMember) GetLike() int32 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *GuildMember) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GuildMember) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *GuildMember) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *GuildMember) GetTrophy() int32 {
	if x != nil {
		return x.Trophy
	}
	return 0
}

func (x *GuildMember) GetStarActivityId() int64 {
	if x != nil {
		return x.StarActivityId
	}
	return 0
}

//公会信息
type GuildInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base    *GuildBaseInfo `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`       //公会基础信息
	Members *GuildMembers  `protobuf:"bytes,2,opt,name=members,proto3" json:"members,omitempty"` //公会成员列表
}

func (x *GuildInfo) Reset() {
	*x = GuildInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildInfo) ProtoMessage() {}

func (x *GuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildInfo.ProtoReflect.Descriptor instead.
func (*GuildInfo) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{3}
}

func (x *GuildInfo) GetBase() *GuildBaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GuildInfo) GetMembers() *GuildMembers {
	if x != nil {
		return x.Members
	}
	return nil
}

//公会成员列表
type GuildMembers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*GuildMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"` //公会成员列表
}

func (x *GuildMembers) Reset() {
	*x = GuildMembers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMembers) ProtoMessage() {}

func (x *GuildMembers) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMembers.ProtoReflect.Descriptor instead.
func (*GuildMembers) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{4}
}

func (x *GuildMembers) GetMembers() []*GuildMember {
	if x != nil {
		return x.Members
	}
	return nil
}

//创建公会
type CSCreateGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Badge      string        `protobuf:"bytes,1,opt,name=badge,proto3" json:"badge,omitempty"`                           //　公会徽章
	OpenType   GuildOpenType `protobuf:"varint,2,opt,name=openType,proto3,enum=GuildOpenType" json:"openType,omitempty"` //  公会类型（0-不可加入，1-可加入，其它后面再扩展）
	LimitLevel int32         `protobuf:"varint,3,opt,name=limitLevel,proto3" json:"limitLevel,omitempty"`                //限制等级
	Name       string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                             //公会名称
	Desc       string        `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`                             //公会简介
	Country    string        `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`                       // 国家
}

func (x *CSCreateGuild) Reset() {
	*x = CSCreateGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSCreateGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSCreateGuild) ProtoMessage() {}

func (x *CSCreateGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSCreateGuild.ProtoReflect.Descriptor instead.
func (*CSCreateGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{5}
}

func (x *CSCreateGuild) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *CSCreateGuild) GetOpenType() GuildOpenType {
	if x != nil {
		return x.OpenType
	}
	return GuildOpenType_NONE1
}

func (x *CSCreateGuild) GetLimitLevel() int32 {
	if x != nil {
		return x.LimitLevel
	}
	return 0
}

func (x *CSCreateGuild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CSCreateGuild) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CSCreateGuild) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

//创建公会响应
type SCCreateGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildInfo *GuildInfo `protobuf:"bytes,1,opt,name=guildInfo,proto3" json:"guildInfo,omitempty"` //公会基础信息
}

func (x *SCCreateGuild) Reset() {
	*x = SCCreateGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCCreateGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCCreateGuild) ProtoMessage() {}

func (x *SCCreateGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCCreateGuild.ProtoReflect.Descriptor instead.
func (*SCCreateGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{6}
}

func (x *SCCreateGuild) GetGuildInfo() *GuildInfo {
	if x != nil {
		return x.GuildInfo
	}
	return nil
}

//加入公会
type CSJoinGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId int64 `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId,omitempty"` //公会ID
}

func (x *CSJoinGuild) Reset() {
	*x = CSJoinGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSJoinGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSJoinGuild) ProtoMessage() {}

func (x *CSJoinGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSJoinGuild.ProtoReflect.Descriptor instead.
func (*CSJoinGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{7}
}

func (x *CSJoinGuild) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

//加入公会响应
type SCJoinGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildInfo *GuildInfo `protobuf:"bytes,1,opt,name=guildInfo,proto3" json:"guildInfo,omitempty"` //公会信息
}

func (x *SCJoinGuild) Reset() {
	*x = SCJoinGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCJoinGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCJoinGuild) ProtoMessage() {}

func (x *SCJoinGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCJoinGuild.ProtoReflect.Descriptor instead.
func (*SCJoinGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{8}
}

func (x *SCJoinGuild) GetGuildInfo() *GuildInfo {
	if x != nil {
		return x.GuildInfo
	}
	return nil
}

//离开公会
type CSLeaveGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId int64 `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId,omitempty"` //玩家id
}

func (x *CSLeaveGuild) Reset() {
	*x = CSLeaveGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSLeaveGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSLeaveGuild) ProtoMessage() {}

func (x *CSLeaveGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSLeaveGuild.ProtoReflect.Descriptor instead.
func (*CSLeaveGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{9}
}

func (x *CSLeaveGuild) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

//离开公会响应
type SCLeaveGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SCLeaveGuild) Reset() {
	*x = SCLeaveGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCLeaveGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCLeaveGuild) ProtoMessage() {}

func (x *SCLeaveGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCLeaveGuild.ProtoReflect.Descriptor instead.
func (*SCLeaveGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{10}
}

func (x *SCLeaveGuild) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

//搜索公会
type CSSearchGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`        //按名字搜索
	GuildId int64  `protobuf:"varint,2,opt,name=guildId,proto3" json:"guildId,omitempty"` //搜索指定公会ID
}

func (x *CSSearchGuild) Reset() {
	*x = CSSearchGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSSearchGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSSearchGuild) ProtoMessage() {}

func (x *CSSearchGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSSearchGuild.ProtoReflect.Descriptor instead.
func (*CSSearchGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{11}
}

func (x *CSSearchGuild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CSSearchGuild) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

type SCSearchGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guilds []*GuildInfo `protobuf:"bytes,1,rep,name=guilds,proto3" json:"guilds,omitempty"`
}

func (x *SCSearchGuild) Reset() {
	*x = SCSearchGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCSearchGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCSearchGuild) ProtoMessage() {}

func (x *SCSearchGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCSearchGuild.ProtoReflect.Descriptor instead.
func (*SCSearchGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{12}
}

func (x *SCSearchGuild) GetGuilds() []*GuildInfo {
	if x != nil {
		return x.Guilds
	}
	return nil
}

//更新公会
type CSUpdateGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId    int64         `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId,omitempty"`                      //公会ID
	LevelLimit int32         `protobuf:"varint,2,opt,name=levelLimit,proto3" json:"levelLimit,omitempty"`                //等级限制
	OpenType   GuildOpenType `protobuf:"varint,3,opt,name=openType,proto3,enum=GuildOpenType" json:"openType,omitempty"` //公会类型
	Badge      string        `protobuf:"bytes,4,opt,name=badge,proto3" json:"badge,omitempty"`                           // 公会徽章
	Desc       string        `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`                             // 公会描述
	Name       string        `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`                             // 公会名字
}

func (x *CSUpdateGuild) Reset() {
	*x = CSUpdateGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSUpdateGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSUpdateGuild) ProtoMessage() {}

func (x *CSUpdateGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSUpdateGuild.ProtoReflect.Descriptor instead.
func (*CSUpdateGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{13}
}

func (x *CSUpdateGuild) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *CSUpdateGuild) GetLevelLimit() int32 {
	if x != nil {
		return x.LevelLimit
	}
	return 0
}

func (x *CSUpdateGuild) GetOpenType() GuildOpenType {
	if x != nil {
		return x.OpenType
	}
	return GuildOpenType_NONE1
}

func (x *CSUpdateGuild) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *CSUpdateGuild) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CSUpdateGuild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//更新公会响应
type SCUpdateGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildInfo *GuildBaseInfo `protobuf:"bytes,1,opt,name=guildInfo,proto3" json:"guildInfo,omitempty"` //公会基础信息
}

func (x *SCUpdateGuild) Reset() {
	*x = SCUpdateGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUpdateGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUpdateGuild) ProtoMessage() {}

func (x *SCUpdateGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUpdateGuild.ProtoReflect.Descriptor instead.
func (*SCUpdateGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{14}
}

func (x *SCUpdateGuild) GetGuildInfo() *GuildBaseInfo {
	if x != nil {
		return x.GuildInfo
	}
	return nil
}

//获得公会信息
type CSGetGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId int64 `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId,omitempty"` //公会ID
}

func (x *CSGetGuild) Reset() {
	*x = CSGetGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSGetGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSGetGuild) ProtoMessage() {}

func (x *CSGetGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSGetGuild.ProtoReflect.Descriptor instead.
func (*CSGetGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{15}
}

func (x *CSGetGuild) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

type SCGetGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildInfo *GuildInfo `protobuf:"bytes,1,opt,name=guildInfo,proto3" json:"guildInfo,omitempty"` //公会信息
}

func (x *SCGetGuild) Reset() {
	*x = SCGetGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCGetGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCGetGuild) ProtoMessage() {}

func (x *SCGetGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCGetGuild.ProtoReflect.Descriptor instead.
func (*SCGetGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{16}
}

func (x *SCGetGuild) GetGuildInfo() *GuildInfo {
	if x != nil {
		return x.GuildInfo
	}
	return nil
}

//推荐公会
type CSRecommendGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSRecommendGuild) Reset() {
	*x = CSRecommendGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRecommendGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRecommendGuild) ProtoMessage() {}

func (x *CSRecommendGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRecommendGuild.ProtoReflect.Descriptor instead.
func (*CSRecommendGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{17}
}

type SCRecommendGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshTime int64            `protobuf:"varint,1,opt,name=refreshTime,proto3" json:"refreshTime,omitempty"` // 刷新时间
	Guilds      []*GuildBaseInfo `protobuf:"bytes,2,rep,name=guilds,proto3" json:"guilds,omitempty"`
}

func (x *SCRecommendGuild) Reset() {
	*x = SCRecommendGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCRecommendGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCRecommendGuild) ProtoMessage() {}

func (x *SCRecommendGuild) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCRecommendGuild.ProtoReflect.Descriptor instead.
func (*SCRecommendGuild) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{18}
}

func (x *SCRecommendGuild) GetRefreshTime() int64 {
	if x != nil {
		return x.RefreshTime
	}
	return 0
}

func (x *SCRecommendGuild) GetGuilds() []*GuildBaseInfo {
	if x != nil {
		return x.Guilds
	}
	return nil
}

type CSMemberUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level    int32  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"` // 成员等级
	Like     int32  `protobuf:"varint,2,opt,name=like,proto3" json:"like,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	HeadIcon string `protobuf:"bytes,4,opt,name=headIcon,proto3" json:"headIcon,omitempty"`
	Channel  int32  `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Star     int32  `protobuf:"varint,6,opt,name=star,proto3" json:"star,omitempty"` // 满级玩法星星
}

func (x *CSMemberUpdate) Reset() {
	*x = CSMemberUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSMemberUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSMemberUpdate) ProtoMessage() {}

func (x *CSMemberUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSMemberUpdate.ProtoReflect.Descriptor instead.
func (*CSMemberUpdate) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{19}
}

func (x *CSMemberUpdate) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CSMemberUpdate) GetLike() int32 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *CSMemberUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CSMemberUpdate) GetHeadIcon() string {
	if x != nil {
		return x.HeadIcon
	}
	return ""
}

func (x *CSMemberUpdate) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *CSMemberUpdate) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

type SCMemberUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level int32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"` // 成员等级
	Like  int32 `protobuf:"varint,2,opt,name=like,proto3" json:"like,omitempty"`
}

func (x *SCMemberUpdate) Reset() {
	*x = SCMemberUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCMemberUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCMemberUpdate) ProtoMessage() {}

func (x *SCMemberUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCMemberUpdate.ProtoReflect.Descriptor instead.
func (*SCMemberUpdate) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{20}
}

func (x *SCMemberUpdate) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SCMemberUpdate) GetLike() int32 {
	if x != nil {
		return x.Like
	}
	return 0
}

type CSUpdateMemberHelpCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	HelpCount int64 `protobuf:"varint,2,opt,name=helpCount,proto3" json:"helpCount,omitempty"`
}

func (x *CSUpdateMemberHelpCount) Reset() {
	*x = CSUpdateMemberHelpCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSUpdateMemberHelpCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSUpdateMemberHelpCount) ProtoMessage() {}

func (x *CSUpdateMemberHelpCount) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSUpdateMemberHelpCount.ProtoReflect.Descriptor instead.
func (*CSUpdateMemberHelpCount) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{21}
}

func (x *CSUpdateMemberHelpCount) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CSUpdateMemberHelpCount) GetHelpCount() int64 {
	if x != nil {
		return x.HelpCount
	}
	return 0
}

type SCUpdateMemberHelpCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	HelpCount int64 `protobuf:"varint,2,opt,name=helpCount,proto3" json:"helpCount,omitempty"`
}

func (x *SCUpdateMemberHelpCount) Reset() {
	*x = SCUpdateMemberHelpCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUpdateMemberHelpCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUpdateMemberHelpCount) ProtoMessage() {}

func (x *SCUpdateMemberHelpCount) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUpdateMemberHelpCount.ProtoReflect.Descriptor instead.
func (*SCUpdateMemberHelpCount) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{22}
}

func (x *SCUpdateMemberHelpCount) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SCUpdateMemberHelpCount) GetHelpCount() int64 {
	if x != nil {
		return x.HelpCount
	}
	return 0
}

// 公会踢除成员
type CSKickMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId int64 `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	GuildId  int64 `protobuf:"varint,2,opt,name=guildId,proto3" json:"guildId,omitempty"`
}

func (x *CSKickMember) Reset() {
	*x = CSKickMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSKickMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSKickMember) ProtoMessage() {}

func (x *CSKickMember) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSKickMember.ProtoReflect.Descriptor instead.
func (*CSKickMember) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{23}
}

func (x *CSKickMember) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *CSKickMember) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

type SCKickMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    PANGU_CODE `protobuf:"varint,1,opt,name=result,proto3,enum=PANGU_CODE" json:"result,omitempty"`
	GuildInfo *GuildInfo `protobuf:"bytes,2,opt,name=guildInfo,proto3" json:"guildInfo,omitempty"` //公会信息
}

func (x *SCKickMember) Reset() {
	*x = SCKickMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCKickMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCKickMember) ProtoMessage() {}

func (x *SCKickMember) ProtoReflect() protoreflect.Message {
	mi := &file_guild_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCKickMember.ProtoReflect.Descriptor instead.
func (*SCKickMember) Descriptor() ([]byte, []int) {
	return file_guild_proto_rawDescGZIP(), []int{24}
}

func (x *SCKickMember) GetResult() PANGU_CODE {
	if x != nil {
		return x.Result
	}
	return PANGU_CODE_PANGU_CODE_UNSPECIFIED
}

func (x *SCKickMember) GetGuildInfo() *GuildInfo {
	if x != nil {
		return x.GuildInfo
	}
	return nil
}

var File_guild_proto protoreflect.FileDescriptor

var file_guild_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63,
	0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xf5, 0x02, 0x0a, 0x0d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x42, 0x61, 0x73,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x61, 0x64, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x42, 0x61, 0x64, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x6f,
	0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6f,
	0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x6c, 0x70, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x68, 0x65, 0x6c, 0x70, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x22, 0xa9, 0x02, 0x0a, 0x0b,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x65, 0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x6b, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x6f, 0x70, 0x68,
	0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x72, 0x6f, 0x70, 0x68, 0x79, 0x12,
	0x26, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x09, 0x47, 0x75, 0x69, 0x6c, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x22, 0x36, 0x0a, 0x0c, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x12, 0x26, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x0d, 0x43, 0x53,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x61, 0x64, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61, 0x64, 0x67,
	0x65, 0x12, 0x2a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4f, 0x70, 0x65, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22,
	0x39, 0x0a, 0x0d, 0x53, 0x43, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69, 0x6c, 0x64,
	0x12, 0x28, 0x0a, 0x09, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x43, 0x53,
	0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0b, 0x53, 0x43, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x12, 0x28, 0x0a, 0x09, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x09, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x28, 0x0a, 0x0c,
	0x43, 0x53, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67,
	0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x43, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3d,
	0x0a, 0x0d, 0x43, 0x53, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x33, 0x0a,
	0x0d, 0x53, 0x43, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x22,
	0x0a, 0x06, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x0d, 0x43, 0x53, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47,
	0x75, 0x69, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x2a,
	0x0a, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x61,
	0x64, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61, 0x64, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x43, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x2c, 0x0a, 0x09, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x47,
	0x75, 0x69, 0x6c, 0x64, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x26, 0x0a, 0x0a, 0x43, 0x53, 0x47, 0x65, 0x74,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22,
	0x36, 0x0a, 0x0a, 0x53, 0x43, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x28, 0x0a,
	0x09, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x53, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x22, 0x5c, 0x0a, 0x10, 0x53,
	0x43, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x06, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x0e, 0x43, 0x53,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65,
	0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65,
	0x61, 0x64, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x74, 0x61, 0x72, 0x22, 0x3a, 0x0a, 0x0e, 0x53, 0x43, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65,
	0x22, 0x4f, 0x0a, 0x17, 0x43, 0x53, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x48, 0x65, 0x6c, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x6c, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x68, 0x65, 0x6c, 0x70, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x4f, 0x0a, 0x17, 0x53, 0x43, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x48, 0x65, 0x6c, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x6c, 0x70, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x68, 0x65, 0x6c, 0x70, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x44, 0x0a, 0x0c, 0x43, 0x53, 0x4b, 0x69, 0x63, 0x6b, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x0c, 0x53, 0x43, 0x4b, 0x69,
	0x63, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x50, 0x41, 0x4e, 0x47, 0x55,
	0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a,
	0x09, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x2f, 0x0a, 0x0d, 0x47, 0x75, 0x69, 0x6c, 0x64,
	0x4f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x4e, 0x45,
	0x31, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x02, 0x2a, 0x23, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4c, 0x4f, 0x42, 0x41, 0x4c, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52, 0x59, 0x10, 0x01, 0x42, 0x17, 0x48,
	0x01, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0xaa, 0x02, 0x0a, 0x4d, 0x4d, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_guild_proto_rawDescOnce sync.Once
	file_guild_proto_rawDescData = file_guild_proto_rawDesc
)

func file_guild_proto_rawDescGZIP() []byte {
	file_guild_proto_rawDescOnce.Do(func() {
		file_guild_proto_rawDescData = protoimpl.X.CompressGZIP(file_guild_proto_rawDescData)
	})
	return file_guild_proto_rawDescData
}

var file_guild_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_guild_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_guild_proto_goTypes = []interface{}{
	(GuildOpenType)(0),              // 0: GuildOpenType
	(RankType)(0),                   // 1: RankType
	(*GetGuild)(nil),                // 2: GetGuild
	(*GuildBaseInfo)(nil),           // 3: GuildBaseInfo
	(*GuildMember)(nil),             // 4: GuildMember
	(*GuildInfo)(nil),               // 5: GuildInfo
	(*GuildMembers)(nil),            // 6: GuildMembers
	(*CSCreateGuild)(nil),           // 7: CSCreateGuild
	(*SCCreateGuild)(nil),           // 8: SCCreateGuild
	(*CSJoinGuild)(nil),             // 9: CSJoinGuild
	(*SCJoinGuild)(nil),             // 10: SCJoinGuild
	(*CSLeaveGuild)(nil),            // 11: CSLeaveGuild
	(*SCLeaveGuild)(nil),            // 12: SCLeaveGuild
	(*CSSearchGuild)(nil),           // 13: CSSearchGuild
	(*SCSearchGuild)(nil),           // 14: SCSearchGuild
	(*CSUpdateGuild)(nil),           // 15: CSUpdateGuild
	(*SCUpdateGuild)(nil),           // 16: SCUpdateGuild
	(*CSGetGuild)(nil),              // 17: CSGetGuild
	(*SCGetGuild)(nil),              // 18: SCGetGuild
	(*CSRecommendGuild)(nil),        // 19: CSRecommendGuild
	(*SCRecommendGuild)(nil),        // 20: SCRecommendGuild
	(*CSMemberUpdate)(nil),          // 21: CSMemberUpdate
	(*SCMemberUpdate)(nil),          // 22: SCMemberUpdate
	(*CSUpdateMemberHelpCount)(nil), // 23: CSUpdateMemberHelpCount
	(*SCUpdateMemberHelpCount)(nil), // 24: SCUpdateMemberHelpCount
	(*CSKickMember)(nil),            // 25: CSKickMember
	(*SCKickMember)(nil),            // 26: SCKickMember
	(PANGU_CODE)(0),                 // 27: PANGU_CODE
}
var file_guild_proto_depIdxs = []int32{
	0,  // 0: GuildBaseInfo.openType:type_name -> GuildOpenType
	3,  // 1: GuildInfo.base:type_name -> GuildBaseInfo
	6,  // 2: GuildInfo.members:type_name -> GuildMembers
	4,  // 3: GuildMembers.members:type_name -> GuildMember
	0,  // 4: CSCreateGuild.openType:type_name -> GuildOpenType
	5,  // 5: SCCreateGuild.guildInfo:type_name -> GuildInfo
	5,  // 6: SCJoinGuild.guildInfo:type_name -> GuildInfo
	5,  // 7: SCSearchGuild.guilds:type_name -> GuildInfo
	0,  // 8: CSUpdateGuild.openType:type_name -> GuildOpenType
	3,  // 9: SCUpdateGuild.guildInfo:type_name -> GuildBaseInfo
	5,  // 10: SCGetGuild.guildInfo:type_name -> GuildInfo
	3,  // 11: SCRecommendGuild.guilds:type_name -> GuildBaseInfo
	27, // 12: SCKickMember.result:type_name -> PANGU_CODE
	5,  // 13: SCKickMember.guildInfo:type_name -> GuildInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_guild_proto_init() }
func file_guild_proto_init() {
	if File_guild_proto != nil {
		return
	}
	file_code_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_guild_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildMembers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSCreateGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCCreateGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSJoinGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCJoinGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSLeaveGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCLeaveGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSSearchGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCSearchGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSUpdateGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUpdateGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSGetGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCGetGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRecommendGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCRecommendGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSMemberUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCMemberUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSUpdateMemberHelpCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUpdateMemberHelpCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSKickMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCKickMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_guild_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guild_proto_goTypes,
		DependencyIndexes: file_guild_proto_depIdxs,
		EnumInfos:         file_guild_proto_enumTypes,
		MessageInfos:      file_guild_proto_msgTypes,
	}.Build()
	File_guild_proto = out.File
	file_guild_proto_rawDesc = nil
	file_guild_proto_goTypes = nil
	file_guild_proto_depIdxs = nil
}
