// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: guild_help.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuildReqHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                              // 帮助标识
	Total             int32              `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                        // 总数
	Count             int32              `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                        // 当前资源数
	Resource          int32              `protobuf:"varint,4,opt,name=resource,proto3" json:"resource,omitempty"`                  // 请求资源类型，eg. 1： 体力； 2：碎片；
	GuildId           int64              `protobuf:"varint,5,opt,name=guildId,proto3" json:"guildId,omitempty"`                    // 公会ID
	Time              int64              `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`                          // 请求时间
	Requester         *UserBaseInfo      `protobuf:"bytes,7,opt,name=requester,proto3" json:"requester,omitempty"`                 // 请求者
	GuildRespHelpList *GuildRespHelpList `protobuf:"bytes,8,opt,name=guildRespHelpList,proto3" json:"guildRespHelpList,omitempty"` // 请求者标识
}

func (x *GuildReqHelp) Reset() {
	*x = GuildReqHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildReqHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildReqHelp) ProtoMessage() {}

func (x *GuildReqHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildReqHelp.ProtoReflect.Descriptor instead.
func (*GuildReqHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{0}
}

func (x *GuildReqHelp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildReqHelp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GuildReqHelp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GuildReqHelp) GetResource() int32 {
	if x != nil {
		return x.Resource
	}
	return 0
}

func (x *GuildReqHelp) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildReqHelp) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GuildReqHelp) GetRequester() *UserBaseInfo {
	if x != nil {
		return x.Requester
	}
	return nil
}

func (x *GuildReqHelp) GetGuildRespHelpList() *GuildRespHelpList {
	if x != nil {
		return x.GuildRespHelpList
	}
	return nil
}

type GuildRespHelpList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildRespHelps []*GuildRespHelp `protobuf:"bytes,1,rep,name=guildRespHelps,proto3" json:"guildRespHelps,omitempty"` // 响应帮助列表
}

func (x *GuildRespHelpList) Reset() {
	*x = GuildRespHelpList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildRespHelpList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRespHelpList) ProtoMessage() {}

func (x *GuildRespHelpList) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRespHelpList.ProtoReflect.Descriptor instead.
func (*GuildRespHelpList) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{1}
}

func (x *GuildRespHelpList) GetGuildRespHelps() []*GuildRespHelp {
	if x != nil {
		return x.GuildRespHelps
	}
	return nil
}

type GuildRespHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                    // 响应帮助标识
	GuildReqHelp *GuildReqHelp `protobuf:"bytes,2,opt,name=guildReqHelp,proto3" json:"guildReqHelp,omitempty"` // 请求帮助
	Time         int64         `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`                // 事件到达服务器时间
	Responser    *UserBaseInfo `protobuf:"bytes,5,opt,name=responser,proto3" json:"responser,omitempty"`       // 响应者
	Ack          bool          `protobuf:"varint,6,opt,name=Ack,proto3" json:"Ack,omitempty"`                  // 是否已消费
}

func (x *GuildRespHelp) Reset() {
	*x = GuildRespHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildRespHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRespHelp) ProtoMessage() {}

func (x *GuildRespHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRespHelp.ProtoReflect.Descriptor instead.
func (*GuildRespHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{2}
}

func (x *GuildRespHelp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildRespHelp) GetGuildReqHelp() *GuildReqHelp {
	if x != nil {
		return x.GuildReqHelp
	}
	return nil
}

func (x *GuildRespHelp) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GuildRespHelp) GetResponser() *UserBaseInfo {
	if x != nil {
		return x.Responser
	}
	return nil
}

func (x *GuildRespHelp) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

// 请求帮助
type CSRequestGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId  int64 `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId,omitempty"`   // 所在公会ID
	Resource int32 `protobuf:"varint,2,opt,name=resource,proto3" json:"resource,omitempty"` // 请求资源类型，eg. 1： 体力； 2：碎片；
	Total    int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`       // 请求资源总数
}

func (x *CSRequestGuildHelp) Reset() {
	*x = CSRequestGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRequestGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRequestGuildHelp) ProtoMessage() {}

func (x *CSRequestGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRequestGuildHelp.ProtoReflect.Descriptor instead.
func (*CSRequestGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{3}
}

func (x *CSRequestGuildHelp) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *CSRequestGuildHelp) GetResource() int32 {
	if x != nil {
		return x.Resource
	}
	return 0
}

func (x *CSRequestGuildHelp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 请求帮助
type SCRequestGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildReqHelp *GuildReqHelp `protobuf:"bytes,1,opt,name=guildReqHelp,proto3" json:"guildReqHelp,omitempty"`
}

func (x *SCRequestGuildHelp) Reset() {
	*x = SCRequestGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCRequestGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCRequestGuildHelp) ProtoMessage() {}

func (x *SCRequestGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCRequestGuildHelp.ProtoReflect.Descriptor instead.
func (*SCRequestGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{4}
}

func (x *SCRequestGuildHelp) GetGuildReqHelp() *GuildReqHelp {
	if x != nil {
		return x.GuildReqHelp
	}
	return nil
}

// 响应帮助
type CSResponseGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqHelpId int64 `protobuf:"varint,1,opt,name=reqHelpId,proto3" json:"reqHelpId,omitempty"` // request help id
	GuildId   int64 `protobuf:"varint,2,opt,name=guildId,proto3" json:"guildId,omitempty"`     // 公会ID
}

func (x *CSResponseGuildHelp) Reset() {
	*x = CSResponseGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSResponseGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSResponseGuildHelp) ProtoMessage() {}

func (x *CSResponseGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSResponseGuildHelp.ProtoReflect.Descriptor instead.
func (*CSResponseGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{5}
}

func (x *CSResponseGuildHelp) GetReqHelpId() int64 {
	if x != nil {
		return x.ReqHelpId
	}
	return 0
}

func (x *CSResponseGuildHelp) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

// 响应帮助
type SCResponseGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildRespHelp *GuildRespHelp `protobuf:"bytes,1,opt,name=guildRespHelp,proto3" json:"guildRespHelp,omitempty"`
}

func (x *SCResponseGuildHelp) Reset() {
	*x = SCResponseGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCResponseGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCResponseGuildHelp) ProtoMessage() {}

func (x *SCResponseGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCResponseGuildHelp.ProtoReflect.Descriptor instead.
func (*SCResponseGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{6}
}

func (x *SCResponseGuildHelp) GetGuildRespHelp() *GuildRespHelp {
	if x != nil {
		return x.GuildRespHelp
	}
	return nil
}

// 消费response help
type CSAckGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespHelpId int64 `protobuf:"varint,1,opt,name=RespHelpId,proto3" json:"RespHelpId,omitempty"` // response help id
}

func (x *CSAckGuildHelp) Reset() {
	*x = CSAckGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSAckGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSAckGuildHelp) ProtoMessage() {}

func (x *CSAckGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSAckGuildHelp.ProtoReflect.Descriptor instead.
func (*CSAckGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{7}
}

func (x *CSAckGuildHelp) GetRespHelpId() int64 {
	if x != nil {
		return x.RespHelpId
	}
	return 0
}

// 消费response help
type SCAckGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 0: 失败， 1：成功
}

func (x *SCAckGuildHelp) Reset() {
	*x = SCAckGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCAckGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCAckGuildHelp) ProtoMessage() {}

func (x *SCAckGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCAckGuildHelp.ProtoReflect.Descriptor instead.
func (*SCAckGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{8}
}

func (x *SCAckGuildHelp) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// list未消费的response help
type CSListGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespHelpId int64 `protobuf:"varint,1,opt,name=respHelpId,proto3" json:"respHelpId,omitempty"` // 提供一个响应help ID，则默认拉取大于该条help的数据
}

func (x *CSListGuildHelp) Reset() {
	*x = CSListGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSListGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSListGuildHelp) ProtoMessage() {}

func (x *CSListGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSListGuildHelp.ProtoReflect.Descriptor instead.
func (*CSListGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{9}
}

func (x *CSListGuildHelp) GetRespHelpId() int64 {
	if x != nil {
		return x.RespHelpId
	}
	return 0
}

// list未消费的response help
type SCListGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildRespHelps []*GuildRespHelp `protobuf:"bytes,1,rep,name=guildRespHelps,proto3" json:"guildRespHelps,omitempty"`
}

func (x *SCListGuildHelp) Reset() {
	*x = SCListGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCListGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCListGuildHelp) ProtoMessage() {}

func (x *SCListGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCListGuildHelp.ProtoReflect.Descriptor instead.
func (*SCListGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{10}
}

func (x *SCListGuildHelp) GetGuildRespHelps() []*GuildRespHelp {
	if x != nil {
		return x.GuildRespHelps
	}
	return nil
}

// 获取公会未达成的request help list
type CSHistoryGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId   int64 `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId,omitempty"`     // 所在公会ID
	ReqHelpId int64 `protobuf:"varint,2,opt,name=reqHelpId,proto3" json:"reqHelpId,omitempty"` // 提供一个请求help ID，则默认拉取大于该条help的数据
}

func (x *CSHistoryGuildHelp) Reset() {
	*x = CSHistoryGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSHistoryGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSHistoryGuildHelp) ProtoMessage() {}

func (x *CSHistoryGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSHistoryGuildHelp.ProtoReflect.Descriptor instead.
func (*CSHistoryGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{11}
}

func (x *CSHistoryGuildHelp) GetGuildId() int64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *CSHistoryGuildHelp) GetReqHelpId() int64 {
	if x != nil {
		return x.ReqHelpId
	}
	return 0
}

// 获取公会未达成的request help list
type SCHistoryGuildHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildReqHelps []*GuildReqHelp `protobuf:"bytes,1,rep,name=guildReqHelps,proto3" json:"guildReqHelps,omitempty"`
}

func (x *SCHistoryGuildHelp) Reset() {
	*x = SCHistoryGuildHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCHistoryGuildHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCHistoryGuildHelp) ProtoMessage() {}

func (x *SCHistoryGuildHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCHistoryGuildHelp.ProtoReflect.Descriptor instead.
func (*SCHistoryGuildHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{12}
}

func (x *SCHistoryGuildHelp) GetGuildReqHelps() []*GuildReqHelp {
	if x != nil {
		return x.GuildReqHelps
	}
	return nil
}

// 获取上次请求时间
type SCUserLastReqHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *SCUserLastReqHelp) Reset() {
	*x = SCUserLastReqHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guild_help_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUserLastReqHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUserLastReqHelp) ProtoMessage() {}

func (x *SCUserLastReqHelp) ProtoReflect() protoreflect.Message {
	mi := &file_guild_help_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUserLastReqHelp.ProtoReflect.Descriptor instead.
func (*SCUserLastReqHelp) Descriptor() ([]byte, []int) {
	return file_guild_help_proto_rawDescGZIP(), []int{13}
}

func (x *SCUserLastReqHelp) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_guild_help_proto protoreflect.FileDescriptor

var file_guild_help_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83,
	0x02, 0x0a, 0x0c, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x40, 0x0a, 0x11, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48,
	0x65, 0x6c, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x11, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x11, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x48, 0x65, 0x6c, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0e, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c,
	0x70, 0x52, 0x0e, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70,
	0x73, 0x22, 0xa5, 0x01, 0x0a, 0x0d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48,
	0x65, 0x6c, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x0c, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x48,
	0x65, 0x6c, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x52, 0x0c, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52,
	0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x41, 0x63, 0x6b, 0x22, 0x60, 0x0a, 0x12, 0x43, 0x53, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65, 0x6c, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x47, 0x0a, 0x12, 0x53,
	0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65, 0x6c,
	0x70, 0x12, 0x31, 0x0a, 0x0c, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x48, 0x65, 0x6c,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52,
	0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x52, 0x0c, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71,
	0x48, 0x65, 0x6c, 0x70, 0x22, 0x4d, 0x0a, 0x13, 0x43, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x72, 0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x69,
	0x6c, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x13, 0x53, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x34, 0x0a, 0x0d, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c,
	0x70, 0x52, 0x0d, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70,
	0x22, 0x30, 0x0a, 0x0e, 0x43, 0x53, 0x41, 0x63, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65,
	0x6c, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70,
	0x49, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x53, 0x43, 0x41, 0x63, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64,
	0x48, 0x65, 0x6c, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x31, 0x0a, 0x0f,
	0x43, 0x53, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65, 0x6c, 0x70, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70, 0x49, 0x64, 0x22,
	0x49, 0x0a, 0x0f, 0x53, 0x43, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65,
	0x6c, 0x70, 0x12, 0x36, 0x0a, 0x0e, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48,
	0x65, 0x6c, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70, 0x52, 0x0e, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x6c, 0x70, 0x73, 0x22, 0x4c, 0x0a, 0x12, 0x43, 0x53,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65, 0x6c, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x71, 0x48, 0x65, 0x6c, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x12, 0x53, 0x43, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x33,
	0x0a, 0x0d, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71,
	0x48, 0x65, 0x6c, 0x70, 0x52, 0x0d, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x48, 0x65,
	0x6c, 0x70, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x43, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x61, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x17, 0x48, 0x01,
	0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0xaa, 0x02, 0x0a, 0x4d, 0x4d, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_guild_help_proto_rawDescOnce sync.Once
	file_guild_help_proto_rawDescData = file_guild_help_proto_rawDesc
)

func file_guild_help_proto_rawDescGZIP() []byte {
	file_guild_help_proto_rawDescOnce.Do(func() {
		file_guild_help_proto_rawDescData = protoimpl.X.CompressGZIP(file_guild_help_proto_rawDescData)
	})
	return file_guild_help_proto_rawDescData
}

var file_guild_help_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_guild_help_proto_goTypes = []interface{}{
	(*GuildReqHelp)(nil),        // 0: GuildReqHelp
	(*GuildRespHelpList)(nil),   // 1: GuildRespHelpList
	(*GuildRespHelp)(nil),       // 2: GuildRespHelp
	(*CSRequestGuildHelp)(nil),  // 3: CSRequestGuildHelp
	(*SCRequestGuildHelp)(nil),  // 4: SCRequestGuildHelp
	(*CSResponseGuildHelp)(nil), // 5: CSResponseGuildHelp
	(*SCResponseGuildHelp)(nil), // 6: SCResponseGuildHelp
	(*CSAckGuildHelp)(nil),      // 7: CSAckGuildHelp
	(*SCAckGuildHelp)(nil),      // 8: SCAckGuildHelp
	(*CSListGuildHelp)(nil),     // 9: CSListGuildHelp
	(*SCListGuildHelp)(nil),     // 10: SCListGuildHelp
	(*CSHistoryGuildHelp)(nil),  // 11: CSHistoryGuildHelp
	(*SCHistoryGuildHelp)(nil),  // 12: SCHistoryGuildHelp
	(*SCUserLastReqHelp)(nil),   // 13: SCUserLastReqHelp
	(*UserBaseInfo)(nil),        // 14: UserBaseInfo
}
var file_guild_help_proto_depIdxs = []int32{
	14, // 0: GuildReqHelp.requester:type_name -> UserBaseInfo
	1,  // 1: GuildReqHelp.guildRespHelpList:type_name -> GuildRespHelpList
	2,  // 2: GuildRespHelpList.guildRespHelps:type_name -> GuildRespHelp
	0,  // 3: GuildRespHelp.guildReqHelp:type_name -> GuildReqHelp
	14, // 4: GuildRespHelp.responser:type_name -> UserBaseInfo
	0,  // 5: SCRequestGuildHelp.guildReqHelp:type_name -> GuildReqHelp
	2,  // 6: SCResponseGuildHelp.guildRespHelp:type_name -> GuildRespHelp
	2,  // 7: SCListGuildHelp.guildRespHelps:type_name -> GuildRespHelp
	0,  // 8: SCHistoryGuildHelp.guildReqHelps:type_name -> GuildReqHelp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_guild_help_proto_init() }
func file_guild_help_proto_init() {
	if File_guild_help_proto != nil {
		return
	}
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_guild_help_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildReqHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildRespHelpList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildRespHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRequestGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCRequestGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSResponseGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCResponseGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSAckGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCAckGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSListGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCListGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSHistoryGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCHistoryGuildHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guild_help_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUserLastReqHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_guild_help_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guild_help_proto_goTypes,
		DependencyIndexes: file_guild_help_proto_depIdxs,
		MessageInfos:      file_guild_help_proto_msgTypes,
	}.Build()
	File_guild_help_proto = out.File
	file_guild_help_proto_rawDesc = nil
	file_guild_help_proto_goTypes = nil
	file_guild_help_proto_depIdxs = nil
}
