// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: levelabconfig.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//请求当前的AB测试配置
type ConfigData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//当前AB测试的版本
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	//当前的关卡
	Level int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	//测试类型 0 未开启 1整套 2分关
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	//当前的AB测试组
	Group string `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	//当前AB测试客户端版本
	ClientVersion string `protobuf:"bytes,5,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
}

func (x *ConfigData) Reset() {
	*x = ConfigData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelabconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigData) ProtoMessage() {}

func (x *ConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_levelabconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigData.ProtoReflect.Descriptor instead.
func (*ConfigData) Descriptor() ([]byte, []int) {
	return file_levelabconfig_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ConfigData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigData) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigData) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

//当前前端的AB测试配置
type LevelABConfigData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//当前的配置
	CurrentData *ConfigData `protobuf:"bytes,1,opt,name=currentData,proto3" json:"currentData,omitempty"`
	//历史配置
	HistoryData []*ConfigData `protobuf:"bytes,2,rep,name=historyData,proto3" json:"historyData,omitempty"`
	//是否已经初始化过
	Inited int32 `protobuf:"varint,3,opt,name=inited,proto3" json:"inited,omitempty"`
}

func (x *LevelABConfigData) Reset() {
	*x = LevelABConfigData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelabconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LevelABConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelABConfigData) ProtoMessage() {}

func (x *LevelABConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_levelabconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelABConfigData.ProtoReflect.Descriptor instead.
func (*LevelABConfigData) Descriptor() ([]byte, []int) {
	return file_levelabconfig_proto_rawDescGZIP(), []int{1}
}

func (x *LevelABConfigData) GetCurrentData() *ConfigData {
	if x != nil {
		return x.CurrentData
	}
	return nil
}

func (x *LevelABConfigData) GetHistoryData() []*ConfigData {
	if x != nil {
		return x.HistoryData
	}
	return nil
}

func (x *LevelABConfigData) GetInited() int32 {
	if x != nil {
		return x.Inited
	}
	return 0
}

//功能的ABTest数据
type ABConfigData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *ABConfigData) Reset() {
	*x = ABConfigData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelabconfig_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ABConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABConfigData) ProtoMessage() {}

func (x *ABConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_levelabconfig_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABConfigData.ProtoReflect.Descriptor instead.
func (*ABConfigData) Descriptor() ([]byte, []int) {
	return file_levelabconfig_proto_rawDescGZIP(), []int{2}
}

func (x *ABConfigData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ABConfigData) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

//玩家当前的ABTest数据
type FunctionABConfigData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs []*ABConfigData `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *FunctionABConfigData) Reset() {
	*x = FunctionABConfigData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelabconfig_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionABConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionABConfigData) ProtoMessage() {}

func (x *FunctionABConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_levelabconfig_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionABConfigData.ProtoReflect.Descriptor instead.
func (*FunctionABConfigData) Descriptor() ([]byte, []int) {
	return file_levelabconfig_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionABConfigData) GetConfigs() []*ABConfigData {
	if x != nil {
		return x.Configs
	}
	return nil
}

type CSGetABConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigData *ABConfigData `protobuf:"bytes,1,opt,name=configData,proto3" json:"configData,omitempty"`
	Types      []string      `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *CSGetABConfig) Reset() {
	*x = CSGetABConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelabconfig_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSGetABConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSGetABConfig) ProtoMessage() {}

func (x *CSGetABConfig) ProtoReflect() protoreflect.Message {
	mi := &file_levelabconfig_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSGetABConfig.ProtoReflect.Descriptor instead.
func (*CSGetABConfig) Descriptor() ([]byte, []int) {
	return file_levelabconfig_proto_rawDescGZIP(), []int{4}
}

func (x *CSGetABConfig) GetConfigData() *ABConfigData {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *CSGetABConfig) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type SCGetABConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigData  *ABConfigData   `protobuf:"bytes,1,opt,name=configData,proto3" json:"configData,omitempty"`
	ConfigDatas []*ABConfigData `protobuf:"bytes,2,rep,name=configDatas,proto3" json:"configDatas,omitempty"`
}

func (x *SCGetABConfig) Reset() {
	*x = SCGetABConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_levelabconfig_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCGetABConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCGetABConfig) ProtoMessage() {}

func (x *SCGetABConfig) ProtoReflect() protoreflect.Message {
	mi := &file_levelabconfig_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCGetABConfig.ProtoReflect.Descriptor instead.
func (*SCGetABConfig) Descriptor() ([]byte, []int) {
	return file_levelabconfig_proto_rawDescGZIP(), []int{5}
}

func (x *SCGetABConfig) GetConfigData() *ABConfigData {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *SCGetABConfig) GetConfigDatas() []*ABConfigData {
	if x != nil {
		return x.ConfigDatas
	}
	return nil
}

var File_levelabconfig_proto protoreflect.FileDescriptor

var file_levelabconfig_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x61, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x11, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x41, 0x42,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x0b, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x0b, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x69, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x6e, 0x69, 0x74, 0x65, 0x64,
	0x22, 0x38, 0x0a, 0x0c, 0x41, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x3f, 0x0a, 0x14, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x27, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x54, 0x0a, 0x0d, 0x43,
	0x53, 0x47, 0x65, 0x74, 0x41, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2d, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x41, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x6f, 0x0a, 0x0d, 0x53, 0x43, 0x47, 0x65, 0x74, 0x41, 0x42, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x2d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x73, 0x42, 0x17, 0x48, 0x01, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0xaa, 0x02,
	0x0a, 0x4d, 0x4d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_levelabconfig_proto_rawDescOnce sync.Once
	file_levelabconfig_proto_rawDescData = file_levelabconfig_proto_rawDesc
)

func file_levelabconfig_proto_rawDescGZIP() []byte {
	file_levelabconfig_proto_rawDescOnce.Do(func() {
		file_levelabconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_levelabconfig_proto_rawDescData)
	})
	return file_levelabconfig_proto_rawDescData
}

var file_levelabconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_levelabconfig_proto_goTypes = []interface{}{
	(*ConfigData)(nil),           // 0: ConfigData
	(*LevelABConfigData)(nil),    // 1: LevelABConfigData
	(*ABConfigData)(nil),         // 2: ABConfigData
	(*FunctionABConfigData)(nil), // 3: FunctionABConfigData
	(*CSGetABConfig)(nil),        // 4: CSGetABConfig
	(*SCGetABConfig)(nil),        // 5: SCGetABConfig
}
var file_levelabconfig_proto_depIdxs = []int32{
	0, // 0: LevelABConfigData.currentData:type_name -> ConfigData
	0, // 1: LevelABConfigData.historyData:type_name -> ConfigData
	2, // 2: FunctionABConfigData.configs:type_name -> ABConfigData
	2, // 3: CSGetABConfig.configData:type_name -> ABConfigData
	2, // 4: SCGetABConfig.configData:type_name -> ABConfigData
	2, // 5: SCGetABConfig.configDatas:type_name -> ABConfigData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_levelabconfig_proto_init() }
func file_levelabconfig_proto_init() {
	if File_levelabconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_levelabconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelabconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LevelABConfigData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelabconfig_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ABConfigData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelabconfig_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionABConfigData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelabconfig_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSGetABConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_levelabconfig_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCGetABConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_levelabconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_levelabconfig_proto_goTypes,
		DependencyIndexes: file_levelabconfig_proto_depIdxs,
		MessageInfos:      file_levelabconfig_proto_msgTypes,
	}.Build()
	File_levelabconfig_proto = out.File
	file_levelabconfig_proto_rawDesc = nil
	file_levelabconfig_proto_goTypes = nil
	file_levelabconfig_proto_depIdxs = nil
}
