// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: mail.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//邮件发送类型
type MailSendType int32

const (
	//指定时间一次发送
	MailSendType_Once MailSendType = 0
	//周期性重复发送
	MailSendType_Repeat MailSendType = 1
)

// Enum value maps for MailSendType.
var (
	MailSendType_name = map[int32]string{
		0: "Once",
		1: "Repeat",
	}
	MailSendType_value = map[string]int32{
		"Once":   0,
		"Repeat": 1,
	}
)

func (x MailSendType) Enum() *MailSendType {
	p := new(MailSendType)
	*p = x
	return p
}

func (x MailSendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailSendType) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[0].Descriptor()
}

func (MailSendType) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[0]
}

func (x MailSendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailSendType.Descriptor instead.
func (MailSendType) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

//邮件类型
type MailType int32

const (
	MailType_Server MailType = 0
	MailType_Local  MailType = 1
)

// Enum value maps for MailType.
var (
	MailType_name = map[int32]string{
		0: "Server",
		1: "Local",
	}
	MailType_value = map[string]int32{
		"Server": 0,
		"Local":  1,
	}
)

func (x MailType) Enum() *MailType {
	p := new(MailType)
	*p = x
	return p
}

func (x MailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailType) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[1].Descriptor()
}

func (MailType) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[1]
}

func (x MailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailType.Descriptor instead.
func (MailType) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

//邮件生成器状态
type MailGeneraterState int32

const (
	//未发送
	MailGeneraterState_UnSend MailGeneraterState = 0
	//发送中
	MailGeneraterState_Sending MailGeneraterState = 1
	//已发送
	MailGeneraterState_Sended MailGeneraterState = 2
	//活动的(重复发送的邮件，未结束的状态)
	MailGeneraterState_Active MailGeneraterState = 3
	//失效(重复发送的邮件，结束的状态)
	MailGeneraterState_InActive MailGeneraterState = 4
	//撤回
	MailGeneraterState_WithDraw MailGeneraterState = 5
)

// Enum value maps for MailGeneraterState.
var (
	MailGeneraterState_name = map[int32]string{
		0: "UnSend",
		1: "Sending",
		2: "Sended",
		3: "Active",
		4: "InActive",
		5: "WithDraw",
	}
	MailGeneraterState_value = map[string]int32{
		"UnSend":   0,
		"Sending":  1,
		"Sended":   2,
		"Active":   3,
		"InActive": 4,
		"WithDraw": 5,
	}
)

func (x MailGeneraterState) Enum() *MailGeneraterState {
	p := new(MailGeneraterState)
	*p = x
	return p
}

func (x MailGeneraterState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailGeneraterState) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[2].Descriptor()
}

func (MailGeneraterState) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[2]
}

func (x MailGeneraterState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailGeneraterState.Descriptor instead.
func (MailGeneraterState) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{2}
}

//邮件操作类型
type MailOperatorType int32

const (
	//请求
	MailOperatorType_Req MailOperatorType = 0
	//修改
	MailOperatorType_Modify MailOperatorType = 1
	//删除
	MailOperatorType_Del MailOperatorType = 2
)

// Enum value maps for MailOperatorType.
var (
	MailOperatorType_name = map[int32]string{
		0: "Req",
		1: "Modify",
		2: "Del",
	}
	MailOperatorType_value = map[string]int32{
		"Req":    0,
		"Modify": 1,
		"Del":    2,
	}
)

func (x MailOperatorType) Enum() *MailOperatorType {
	p := new(MailOperatorType)
	*p = x
	return p
}

func (x MailOperatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailOperatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[3].Descriptor()
}

func (MailOperatorType) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[3]
}

func (x MailOperatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailOperatorType.Descriptor instead.
func (MailOperatorType) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{3}
}

//邮件状态
type MailStateType int32

const (
	//未读
	MailStateType_UnRead MailStateType = 0
	//已读
	MailStateType_Readed MailStateType = 1
)

// Enum value maps for MailStateType.
var (
	MailStateType_name = map[int32]string{
		0: "UnRead",
		1: "Readed",
	}
	MailStateType_value = map[string]int32{
		"UnRead": 0,
		"Readed": 1,
	}
)

func (x MailStateType) Enum() *MailStateType {
	p := new(MailStateType)
	*p = x
	return p
}

func (x MailStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[4].Descriptor()
}

func (MailStateType) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[4]
}

func (x MailStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailStateType.Descriptor instead.
func (MailStateType) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{4}
}

//邮件扩展条件
type MailConditionEx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//最小登录时间
	MinLoginDay int32 `protobuf:"varint,1,opt,name=minLoginDay,proto3" json:"minLoginDay,omitempty"`
	//最大登录时间
	MaxLoginDay int32 `protobuf:"varint,2,opt,name=maxLoginDay,proto3" json:"maxLoginDay,omitempty"`
	//最小付费额
	MinPay int32 `protobuf:"varint,3,opt,name=minPay,proto3" json:"minPay,omitempty"`
	//最大付费额
	MaxPay int32 `protobuf:"varint,4,opt,name=maxPay,proto3" json:"maxPay,omitempty"`
	//有效期(int格式的日期，在此日期之前有效)
	Validity int32 `protobuf:"varint,5,opt,name=validity,proto3" json:"validity,omitempty"`
}

func (x *MailConditionEx) Reset() {
	*x = MailConditionEx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailConditionEx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailConditionEx) ProtoMessage() {}

func (x *MailConditionEx) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailConditionEx.ProtoReflect.Descriptor instead.
func (*MailConditionEx) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailConditionEx) GetMinLoginDay() int32 {
	if x != nil {
		return x.MinLoginDay
	}
	return 0
}

func (x *MailConditionEx) GetMaxLoginDay() int32 {
	if x != nil {
		return x.MaxLoginDay
	}
	return 0
}

func (x *MailConditionEx) GetMinPay() int32 {
	if x != nil {
		return x.MinPay
	}
	return 0
}

func (x *MailConditionEx) GetMaxPay() int32 {
	if x != nil {
		return x.MaxPay
	}
	return 0
}

func (x *MailConditionEx) GetValidity() int32 {
	if x != nil {
		return x.Validity
	}
	return 0
}

type MailContentData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//语言类型
	LanguageType int32 `protobuf:"varint,1,opt,name=languageType,proto3" json:"languageType,omitempty"`
	//标题
	Tittle string `protobuf:"bytes,2,opt,name=tittle,proto3" json:"tittle,omitempty"`
	//内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MailContentData) Reset() {
	*x = MailContentData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailContentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailContentData) ProtoMessage() {}

func (x *MailContentData) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailContentData.ProtoReflect.Descriptor instead.
func (*MailContentData) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

func (x *MailContentData) GetLanguageType() int32 {
	if x != nil {
		return x.LanguageType
	}
	return 0
}

func (x *MailContentData) GetTittle() string {
	if x != nil {
		return x.Tittle
	}
	return ""
}

func (x *MailContentData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

//邮件数据
type MailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//邮件ID
	MailID int64 `protobuf:"varint,1,opt,name=mailID,proto3" json:"mailID,omitempty"`
	//邮件的内容
	MailContent []*MailContentData `protobuf:"bytes,2,rep,name=mailContent,proto3" json:"mailContent,omitempty"`
	//附件
	Mats []*MaterialJson `protobuf:"bytes,3,rep,name=mats,proto3" json:"mats,omitempty"`
	//创建时间
	CreateTime int64 `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	//邮件状态
	State MailStateType `protobuf:"varint,5,opt,name=state,proto3,enum=MailStateType" json:"state,omitempty"`
	//版本号
	Version []int32 `protobuf:"varint,6,rep,packed,name=version,proto3" json:"version,omitempty"`
	//邮件类型 0 服务器邮件 1 本地邮件
	Type MailType `protobuf:"varint,7,opt,name=type,proto3,enum=MailType" json:"type,omitempty"`
}

func (x *MailData) Reset() {
	*x = MailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailData) ProtoMessage() {}

func (x *MailData) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailData.ProtoReflect.Descriptor instead.
func (*MailData) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{2}
}

func (x *MailData) GetMailID() int64 {
	if x != nil {
		return x.MailID
	}
	return 0
}

func (x *MailData) GetMailContent() []*MailContentData {
	if x != nil {
		return x.MailContent
	}
	return nil
}

func (x *MailData) GetMats() []*MaterialJson {
	if x != nil {
		return x.Mats
	}
	return nil
}

func (x *MailData) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *MailData) GetState() MailStateType {
	if x != nil {
		return x.State
	}
	return MailStateType_UnRead
}

func (x *MailData) GetVersion() []int32 {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *MailData) GetType() MailType {
	if x != nil {
		return x.Type
	}
	return MailType_Server
}

//已经发送的全局邮件数据
type SendedMailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendedMailID int64 `protobuf:"varint,1,opt,name=sendedMailID,proto3" json:"sendedMailID,omitempty"`
	Validity     int32 `protobuf:"varint,2,opt,name=validity,proto3" json:"validity,omitempty"`
	SendTime     int64 `protobuf:"varint,3,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
}

func (x *SendedMailData) Reset() {
	*x = SendedMailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendedMailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendedMailData) ProtoMessage() {}

func (x *SendedMailData) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendedMailData.ProtoReflect.Descriptor instead.
func (*SendedMailData) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{3}
}

func (x *SendedMailData) GetSendedMailID() int64 {
	if x != nil {
		return x.SendedMailID
	}
	return 0
}

func (x *SendedMailData) GetValidity() int32 {
	if x != nil {
		return x.Validity
	}
	return 0
}

func (x *SendedMailData) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

//玩家收到过的邮件ID
type PlayerMailIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailIds []int64 `protobuf:"varint,1,rep,packed,name=mailIds,proto3" json:"mailIds,omitempty"`
}

func (x *PlayerMailIds) Reset() {
	*x = PlayerMailIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMailIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMailIds) ProtoMessage() {}

func (x *PlayerMailIds) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMailIds.ProtoReflect.Descriptor instead.
func (*PlayerMailIds) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerMailIds) GetMailIds() []int64 {
	if x != nil {
		return x.MailIds
	}
	return nil
}

//玩家的邮件
type PlayerMails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mails []*MailData `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails,omitempty"`
}

func (x *PlayerMails) Reset() {
	*x = PlayerMails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMails) ProtoMessage() {}

func (x *PlayerMails) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMails.ProtoReflect.Descriptor instead.
func (*PlayerMails) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerMails) GetMails() []*MailData {
	if x != nil {
		return x.Mails
	}
	return nil
}

//全服邮件的数据
type GlobalMailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailCondition *MailConditionEx `protobuf:"bytes,1,opt,name=mailCondition,proto3" json:"mailCondition,omitempty"`
	MailData      *MailData        `protobuf:"bytes,2,opt,name=mailData,proto3" json:"mailData,omitempty"`
}

func (x *GlobalMailData) Reset() {
	*x = GlobalMailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalMailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalMailData) ProtoMessage() {}

func (x *GlobalMailData) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalMailData.ProtoReflect.Descriptor instead.
func (*GlobalMailData) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{6}
}

func (x *GlobalMailData) GetMailCondition() *MailConditionEx {
	if x != nil {
		return x.MailCondition
	}
	return nil
}

func (x *GlobalMailData) GetMailData() *MailData {
	if x != nil {
		return x.MailData
	}
	return nil
}

type CSMailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperatorType MailOperatorType `protobuf:"varint,1,opt,name=operatorType,proto3,enum=MailOperatorType" json:"operatorType,omitempty"`
	MailID       []int64          `protobuf:"varint,2,rep,packed,name=mailID,proto3" json:"mailID,omitempty"`
}

func (x *CSMailData) Reset() {
	*x = CSMailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSMailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSMailData) ProtoMessage() {}

func (x *CSMailData) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSMailData.ProtoReflect.Descriptor instead.
func (*CSMailData) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{7}
}

func (x *CSMailData) GetOperatorType() MailOperatorType {
	if x != nil {
		return x.OperatorType
	}
	return MailOperatorType_Req
}

func (x *CSMailData) GetMailID() []int64 {
	if x != nil {
		return x.MailID
	}
	return nil
}

type SCMailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailData *PlayerMails `protobuf:"bytes,1,opt,name=mailData,proto3" json:"mailData,omitempty"`
}

func (x *SCMailData) Reset() {
	*x = SCMailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCMailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCMailData) ProtoMessage() {}

func (x *SCMailData) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCMailData.ProtoReflect.Descriptor instead.
func (*SCMailData) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{8}
}

func (x *SCMailData) GetMailData() *PlayerMails {
	if x != nil {
		return x.MailData
	}
	return nil
}

type LocalMailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mails      []*MailData `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails,omitempty"`
	IncrMailID int64       `protobuf:"varint,2,opt,name=incrMailID,proto3" json:"incrMailID,omitempty"`
}

func (x *LocalMailData) Reset() {
	*x = LocalMailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mail_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalMailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalMailData) ProtoMessage() {}

func (x *LocalMailData) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalMailData.ProtoReflect.Descriptor instead.
func (*LocalMailData) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{9}
}

func (x *LocalMailData) GetMails() []*MailData {
	if x != nil {
		return x.Mails
	}
	return nil
}

func (x *LocalMailData) GetIncrMailID() int64 {
	if x != nil {
		return x.IncrMailID
	}
	return 0
}

var File_mail_proto protoreflect.FileDescriptor

var file_mail_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x0f, 0x4d,
	0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x12, 0x20,
	0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44,
	0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x50, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x50, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61,
	0x78, 0x50, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x50,
	0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x22, 0x67,
	0x0a, 0x0f, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xf8, 0x01, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x12, 0x32, 0x0a, 0x0b,
	0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x0b, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x21, 0x0a, 0x04, 0x6d, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4a, 0x73, 0x6f, 0x6e, 0x52, 0x04, 0x6d,
	0x61, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x09, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x6c, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4d, 0x61, 0x69, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4d, 0x61,
	0x69, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x29, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x2e, 0x0a, 0x0b, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x6d, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x61, 0x69, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x6f, 0x0a, 0x0e, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a,
	0x0d, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x52, 0x0d, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5b, 0x0a, 0x0a,
	0x43, 0x53, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0c, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x22, 0x36, 0x0a, 0x0a, 0x53, 0x43, 0x4d,
	0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x50, 0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1f, 0x0a, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x6d, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x63, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x63, 0x72, 0x4d, 0x61, 0x69,
	0x6c, 0x49, 0x44, 0x2a, 0x24, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x6e, 0x63, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x10, 0x01, 0x2a, 0x21, 0x0a, 0x08, 0x4d, 0x61, 0x69,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x10, 0x01, 0x2a, 0x61, 0x0a, 0x12,
	0x4d, 0x61, 0x69, 0x6c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10,
	0x04, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x69, 0x74, 0x68, 0x44, 0x72, 0x61, 0x77, 0x10, 0x05, 0x2a,
	0x30, 0x0a, 0x10, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x10,
	0x02, 0x2a, 0x27, 0x0a, 0x0d, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x65, 0x61, 0x64, 0x65, 0x64, 0x10, 0x01, 0x42, 0x17, 0x48, 0x01, 0x5a, 0x06,
	0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0xaa, 0x02, 0x0a, 0x4d, 0x4d, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mail_proto_rawDescOnce sync.Once
	file_mail_proto_rawDescData = file_mail_proto_rawDesc
)

func file_mail_proto_rawDescGZIP() []byte {
	file_mail_proto_rawDescOnce.Do(func() {
		file_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_mail_proto_rawDescData)
	})
	return file_mail_proto_rawDescData
}

var file_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mail_proto_goTypes = []interface{}{
	(MailSendType)(0),       // 0: MailSendType
	(MailType)(0),           // 1: MailType
	(MailGeneraterState)(0), // 2: MailGeneraterState
	(MailOperatorType)(0),   // 3: MailOperatorType
	(MailStateType)(0),      // 4: MailStateType
	(*MailConditionEx)(nil), // 5: MailConditionEx
	(*MailContentData)(nil), // 6: MailContentData
	(*MailData)(nil),        // 7: MailData
	(*SendedMailData)(nil),  // 8: SendedMailData
	(*PlayerMailIds)(nil),   // 9: PlayerMailIds
	(*PlayerMails)(nil),     // 10: PlayerMails
	(*GlobalMailData)(nil),  // 11: GlobalMailData
	(*CSMailData)(nil),      // 12: CSMailData
	(*SCMailData)(nil),      // 13: SCMailData
	(*LocalMailData)(nil),   // 14: LocalMailData
	(*MaterialJson)(nil),    // 15: MaterialJson
}
var file_mail_proto_depIdxs = []int32{
	6,  // 0: MailData.mailContent:type_name -> MailContentData
	15, // 1: MailData.mats:type_name -> MaterialJson
	4,  // 2: MailData.state:type_name -> MailStateType
	1,  // 3: MailData.type:type_name -> MailType
	7,  // 4: PlayerMails.mails:type_name -> MailData
	5,  // 5: GlobalMailData.mailCondition:type_name -> MailConditionEx
	7,  // 6: GlobalMailData.mailData:type_name -> MailData
	3,  // 7: CSMailData.operatorType:type_name -> MailOperatorType
	10, // 8: SCMailData.mailData:type_name -> PlayerMails
	7,  // 9: LocalMailData.mails:type_name -> MailData
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_mail_proto_init() }
func file_mail_proto_init() {
	if File_mail_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailConditionEx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailContentData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendedMailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMailIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalMailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSMailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCMailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mail_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalMailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mail_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mail_proto_goTypes,
		DependencyIndexes: file_mail_proto_depIdxs,
		EnumInfos:         file_mail_proto_enumTypes,
		MessageInfos:      file_mail_proto_msgTypes,
	}.Build()
	File_mail_proto = out.File
	file_mail_proto_rawDesc = nil
	file_mail_proto_goTypes = nil
	file_mail_proto_depIdxs = nil
}
