// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: rank.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuildRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grs []*GuildBaseInfo `protobuf:"bytes,1,rep,name=grs,proto3" json:"grs,omitempty"`
}

func (x *GuildRank) Reset() {
	*x = GuildRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRank) ProtoMessage() {}

func (x *GuildRank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRank.ProtoReflect.Descriptor instead.
func (*GuildRank) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{0}
}

func (x *GuildRank) GetGrs() []*GuildBaseInfo {
	if x != nil {
		return x.Grs
	}
	return nil
}

type UserRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urs []*UserBaseInfo `protobuf:"bytes,1,rep,name=urs,proto3" json:"urs,omitempty"`
}

func (x *UserRank) Reset() {
	*x = UserRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRank) ProtoMessage() {}

func (x *UserRank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRank.ProtoReflect.Descriptor instead.
func (*UserRank) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{1}
}

func (x *UserRank) GetUrs() []*UserBaseInfo {
	if x != nil {
		return x.Urs
	}
	return nil
}

type CSUserRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankType string `protobuf:"bytes,1,opt,name=rankType,proto3" json:"rankType,omitempty"` // 排行榜类型 传国家名，默认"global"
}

func (x *CSUserRank) Reset() {
	*x = CSUserRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSUserRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSUserRank) ProtoMessage() {}

func (x *CSUserRank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSUserRank.ProtoReflect.Descriptor instead.
func (*CSUserRank) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{2}
}

func (x *CSUserRank) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

type SCUserRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankType string    `protobuf:"bytes,1,opt,name=rankType,proto3" json:"rankType,omitempty"` // 排行榜类型 global
	UserRank *UserRank `protobuf:"bytes,2,opt,name=userRank,proto3" json:"userRank,omitempty"`
}

func (x *SCUserRank) Reset() {
	*x = SCUserRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUserRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUserRank) ProtoMessage() {}

func (x *SCUserRank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUserRank.ProtoReflect.Descriptor instead.
func (*SCUserRank) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{3}
}

func (x *SCUserRank) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *SCUserRank) GetUserRank() *UserRank {
	if x != nil {
		return x.UserRank
	}
	return nil
}

//公会排行榜
type CSRankGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankType string `protobuf:"bytes,1,opt,name=rankType,proto3" json:"rankType,omitempty"` //请求排行榜类型
}

func (x *CSRankGuild) Reset() {
	*x = CSRankGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRankGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRankGuild) ProtoMessage() {}

func (x *CSRankGuild) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRankGuild.ProtoReflect.Descriptor instead.
func (*CSRankGuild) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{4}
}

func (x *CSRankGuild) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

type SCRankGuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankType string     `protobuf:"bytes,1,opt,name=rankType,proto3" json:"rankType,omitempty"` // 排行榜类型
	Rank     *GuildRank `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`         // 排行榜
}

func (x *SCRankGuild) Reset() {
	*x = SCRankGuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rank_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCRankGuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCRankGuild) ProtoMessage() {}

func (x *SCRankGuild) ProtoReflect() protoreflect.Message {
	mi := &file_rank_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCRankGuild.ProtoReflect.Descriptor instead.
func (*SCRankGuild) Descriptor() ([]byte, []int) {
	return file_rank_proto_rawDescGZIP(), []int{5}
}

func (x *SCRankGuild) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *SCRankGuild) GetRank() *GuildRank {
	if x != nil {
		return x.Rank
	}
	return nil
}

var File_rank_proto protoreflect.FileDescriptor

var file_rank_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x09, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x61,
	0x6e, 0x6b, 0x12, 0x20, 0x0a, 0x03, 0x67, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x03, 0x67, 0x72, 0x73, 0x22, 0x2b, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b,
	0x12, 0x1f, 0x0a, 0x03, 0x75, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x75, 0x72,
	0x73, 0x22, 0x28, 0x0a, 0x0a, 0x43, 0x53, 0x55, 0x73, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4f, 0x0a, 0x0a, 0x53,
	0x43, 0x55, 0x73, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x6e,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x61, 0x6e,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x52, 0x61, 0x6e,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x61,
	0x6e, 0x6b, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x22, 0x29, 0x0a, 0x0b,
	0x43, 0x53, 0x52, 0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x49, 0x0a, 0x0b, 0x53, 0x43, 0x52, 0x61, 0x6e,
	0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x04, 0x72, 0x61,
	0x6e, 0x6b, 0x42, 0x17, 0x48, 0x01, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0xaa, 0x02,
	0x0a, 0x4d, 0x4d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rank_proto_rawDescOnce sync.Once
	file_rank_proto_rawDescData = file_rank_proto_rawDesc
)

func file_rank_proto_rawDescGZIP() []byte {
	file_rank_proto_rawDescOnce.Do(func() {
		file_rank_proto_rawDescData = protoimpl.X.CompressGZIP(file_rank_proto_rawDescData)
	})
	return file_rank_proto_rawDescData
}

var file_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rank_proto_goTypes = []interface{}{
	(*GuildRank)(nil),     // 0: GuildRank
	(*UserRank)(nil),      // 1: UserRank
	(*CSUserRank)(nil),    // 2: CSUserRank
	(*SCUserRank)(nil),    // 3: SCUserRank
	(*CSRankGuild)(nil),   // 4: CSRankGuild
	(*SCRankGuild)(nil),   // 5: SCRankGuild
	(*GuildBaseInfo)(nil), // 6: GuildBaseInfo
	(*UserBaseInfo)(nil),  // 7: UserBaseInfo
}
var file_rank_proto_depIdxs = []int32{
	6, // 0: GuildRank.grs:type_name -> GuildBaseInfo
	7, // 1: UserRank.urs:type_name -> UserBaseInfo
	1, // 2: SCUserRank.userRank:type_name -> UserRank
	0, // 3: SCRankGuild.rank:type_name -> GuildRank
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rank_proto_init() }
func file_rank_proto_init() {
	if File_rank_proto != nil {
		return
	}
	file_guild_proto_init()
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSUserRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUserRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRankGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rank_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCRankGuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rank_proto_goTypes,
		DependencyIndexes: file_rank_proto_depIdxs,
		MessageInfos:      file_rank_proto_msgTypes,
	}.Build()
	File_rank_proto = out.File
	file_rank_proto_rawDesc = nil
	file_rank_proto_goTypes = nil
	file_rank_proto_depIdxs = nil
}
